# Generated by Django 5.2.7 on 2026-05-24 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.IntegerField(null=True)),
                ('tg_username', models.CharField(max_length=32, null=True)),
                ('chat_id', models.IntegerField(null=True)),
                ('tg_activation_date', models.DateTimeField(null=True)),
                ('timezone', models.CharField(max_length=35)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
