FROM nginx:1.27-alpine
# начальный образ уже создает пользователя nginx внутри контейнера

# Удаляем стандартную конфигурацию и создаем директории для логов и ssl ключей
RUN rm /etc/nginx/conf.d/default.conf && \
    mkdir -p /var/log/nginx && \
    mkdir -p /etc/nginx/ssl

# Копируем основные файлы конфигурации (2 шт.)
COPY nginx.conf mime.types /etc/nginx/

# Порт внутри контейнера
EXPOSE 80

# Запускаем nginx в foreground 
# (запрещаем nginx выходить в фоновый режим и удерживаем внутри контейнера)
CMD ["nginx", "-g", "daemon off;"]
