# Generated by Django 5.2.7 on 2026-05-24 05:07

import django.db.models.deletion
import functools
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('w', 'white'), ('g', 'green'), ('b', 'blue'), ('y', 'yellow'), ('r', 'red')], default='w', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('file', models.ImageField(upload_to=functools.partial(main.models.get_unique_path, *(), **{'subfolder': 'records'}))),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('msg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.message')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('msg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.message')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('w', 'white'), ('g', 'green'), ('b', 'blue'), ('y', 'yellow'), ('r', 'red')], default='w', max_length=1)),
                ('nested_folders', models.TextField(blank=True, default='')),
                ('nested_objects', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='main.noticefolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('w', 'white'), ('g', 'green'), ('b', 'blue'), ('y', 'yellow'), ('r', 'red')], default='w', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('next_date', models.DateField()),
                ('time', models.TimeField()),
                ('period', models.CharField(blank=True, max_length=9, null=True)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='main.noticefolder')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('file', models.ImageField(upload_to=functools.partial(main.models.get_unique_path, *(), **{'subfolder': 'notices'}))),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.notice')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.record'),
        ),
        migrations.CreateModel(
            name='RecordFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('w', 'white'), ('g', 'green'), ('b', 'blue'), ('y', 'yellow'), ('r', 'red')], default='w', max_length=1)),
                ('nested_folders', models.TextField(blank=True, default='')),
                ('nested_objects', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='main.recordfolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='record',
            name='folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.recordfolder'),
        ),
    ]
